### ISSUE TITLE
No connector for [rabbitmq]

### ISSUE THREAD

**Issue by vkoori** [keepsuit/laravel-opentelemetry#22]
When I try to install the keepsuit/laravel-opentelemetry package alongside vyuldashev/laravel-queue-rabbitmq, I encounter the following error message:
"No connector for [rabbitmq]." The exception details are: "[object] (InvalidArgumentException(code: 0): No connector for [rabbitmq]. at /var/www/html/main-service-php/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php:178)"

**Comment by cappuc** [comment]
Instrumentations are registered in the package boot but I think that the problem is that `vyuldashev/laravel-queue-rabbitmq` register the rabbitmq connector in the boot method and laravel registers this package before `laravel-queue-rabbitmq` so when e register instrumentations the rabbitmq connector is not yet registered.

If they move the rabbitmq connector registration to the register method it should work.

Anyway I will try to delay the instrumentations registration after all packages are booted.

**Comment by vkoori** [comment]
Yes, I checked the code and it is exactly as you say but It is not possible to add a addConnector to the `register` method, because there is no queue key (QueueManager) in the app register yet. we can addConnector just in `boot` method.

It will be great if you can register the instrumentation after booted all the packages

**Comment by vkoori** [comment]
I resolved this issue by disabling the auto-discovery feature using the `dont-discover` setting in `composer.json` and manually setting the provider in `config/app.php`.

**Comment by cappuc** [comment]
Hi @vkoori,
can you try with the latest beta release [v1.0.0-beta4](https://github.com/keepsuit/laravel-opentelemetry/releases/tag/1.0.0-beta4)?

**Comment by vkoori** [comment]
I love you :D
with this version fixed
